account/urls.py
from django.conf.urls import url
from django.urls import path, include
from .views import register, view_client,login, activate, account_activation_sent, logout, index,home

# SET THE NAMESPACE!
app_name = 'account'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('login/', login, name='login'),
    path('index/', index, name='index'),
    path('home/', home, name='home'),
    path('<int:loan_id>view_client/', view_client, name='view_client'),
    url(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
]

companies/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views 
# from .views import *
# SET THE NAMESPACE!
app_name = 'companies'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    # path("loan_history_listing/", views.Loan_HistoryListing.as_view(), name = 'listing'),
    url(r'^api/v1.0/application_scoring[/]?$', views.ApplicationAPIView.as_view(), name='application_scoring_view'),
    url(r'^api/v1.0/behavioral_scoring[/]?$', views.BehavioralAPIView.as_view(), name='behavioral_scoring_view'),
    url(r'^api/v1.0/retention_scoring[/]?$', views.RetentionAPIView.as_view(), name='retention_scoring_view'),
    path("ajax/business/", views.getBusiness, name = 'get_businesses'),
    path("ajax/mortage/", views.getMortage, name = 'get_mortages'),
    path("ajax/school/", views.getSchool, name = 'get_schools'),
    path("ajax/funeral/", views.getFuneral, name = 'get_funerals'),
    path('data_for_charts', views.data_for_charts, name="data_for_charts"),
    path('data_aggretation', views.data_aggretation, name="data_aggretation"),
    path('<int:loan_id>/application_report_export_csv/$', views.application_report_export_csv, name="application_report_export_csv"),
    path('<int:loan_id>/application_report/$', views.application_report, name="application_report"),
    path('index/$', views.HomeView.as_view(), name="index"),    
    # path('', views.HomeView.as_view(), name="index"), 
    url(
        r"^index/(?P<user_id>.+)", views.HomeView.as_view(), name="index"
    ),

    path('income_classifier/', views.ApplicationAnalyticsResultsView.as_view(), name="income_classifier"),    
    path('application_analytics/', views.ApplicationAnalyticsResultsView.as_view(), name='application_analytics'),
    path('retention_analytics/', views.RetentionAnalyticsResultsView.as_view(), name='retention_analytics'),
    path('behavioral_analytics/', views.BehavioralAnalyticsResultsView.as_view(), name='behavioral_analytics'),
    path('client_profile/', views.client_profile, name='client_profile'),
    path('application_report/', views.application_report, name='application_report'),
    path('application_report_export_csv/', views.application_report_export_csv, name='application_report_export_csv'),
    path('officer_profile/', views.officer_profile, name='officer_profile'),
    path('live_app_score_pred/', views.live_app_score_pred, name='live_app_score_pred'),

    path('reports/', views.reports, name='reports'),
    path('articles/', views.articles, name='articles'),
   
]

fintechapp/urls.py
# backend/server/server/urls.py file
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from account.views import home
from companies import views
from apps.endpoints.urls import urlpatterns as endpoints_urlpatterns
urlpatterns = [
    path('', home, name='home'),
    path('companies_home_dash', views.HomeView.as_view(), name="companies_home_dash"),
    path('admin/', admin.site.urls),
    path('companies/', include('companies.urls')),
    path('d_processor/', include('d_processor.urls')),
    path('account/', include('account.urls')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
]

urlpatterns += endpoints_urlpatterns
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/account_base/base.html
<!-- set bodyTheme = "u-card-v1" -->
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Financial Paradise</title>

    <!-- Global stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet"
        type="text/css">
    <link href="{% static 'account/global_assets/css/icons/icomoon/styles.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'account/assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'account/assets/css/core.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'account/assets/css/components.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'account/assets/css/colors.min.css' %}" rel="stylesheet" type="text/css">
    <!-- /global stylesheets -->




</head>

<body class="login-container">
    {% include 'account/base/header.html' %}
    <!-- Page container -->
    <div class="page-container">

        <!-- Page content -->
        <div class="page-content">

            <!-- Main content -->
            <div class="content-wrapper">
                {% block content %} {% endblock %}
            </div>
        </div>
    </div>


    <!-- Core JS files -->
    <script src="{% static 'account/global_assets/js/plugins/loaders/pace.min.js' %}"></script>
    <script src="{% static 'account/global_assets/js/core/libraries/jquery.min.js' %}"></script>
    <script src="{% static 'account/global_assets/js/core/libraries/bootstrap.min.js' %}"></script>
    <script src="{% static 'account/global_assets/js/plugins/loaders/blockui.min.js' %}"></script>
    <script src="{% static 'account/global_assets/js/plugins/ui/nicescroll.min.js' %}"></script>
    <script src="{% static 'account/global_assets/js/plugins/ui/drilldown.js' %}"></script>
    <!-- /core JS files -->

    <!-- Theme JS files -->
    <!-- Theme JS files -->
    <script src="{% static 'account/global_assets/js/plugins/forms/selects/bootstrap_select.min.js' %}"></script>

    <script src="{% static 'account/assets/js/app.js' %}"></script>
    <script src="{% static 'account/global_assets/js/demo_pages/form_bootstrap_select.js' %}"></script>
    <!-- /theme JS files -->
    <script src="{% static 'account/global_assets/js/plugins/forms/styling/uniform.min.js' %}"></script>

    <script src="{% static 'account/assets/js/app.js' %}"></script>
    <script src="{% static 'account/global_assets/js/demo_pages/login.js' %}"></script>
    <script src="{% static 'account/global_assets/js/plugins/forms/selects/select2.min.js' %}"></script>

    <script src="{% static 'account/global_assets/js/demo_pages/form_select2.js' %}"></script>
    <!-- /theme JS files -->


    <!-- Footer -->
    <div class="footer text-muted text-center">
        &copy; 2020. <a href="#">Financial Paradise</a> by <a href="http://dreatolfintech.com/" target="_blank">Dreatol
            FinTech</a>
    </div>
    <!-- /footer -->

</body>

</html>

templates/account_base/body.html
{% include 'base/base.html' %}
<div class="col g-ml-45 g-ml-0--lg g-pb-65--md">

    {% block content %} {% endblock %}

</div>

templates/account_base/footer.html
<!-- Theme JS files -->
<script src="{% static 'global_assets/js/plugins/visualization/d3/d3.min.js' %}"></script>
<script src="{% static 'global_assets/js/plugins/visualization/d3/d3_tooltip.js' %}"></script>
<script src="{% static 'global_assets/js/plugins/forms/styling/switchery.min.js' %}"></script>
<script src="{% static 'global_assets/js/plugins/forms/selects/bootstrap_multiselect.js' %}"></script>
<script src="{% static 'global_assets/js/plugins/ui/moment/moment.min.js' %}"></script>
<script src="{% static 'global_assets/js/plugins/pickers/daterangepicker.js' %}"></script>
<script src="{% static 'global_assets/js/plugins/ui/headroom/headroom.min.js' %}"></script>
<script src="{% static 'global_assets/js/plugins/ui/headroom/headroom_jquery.min.js' %}"></script>

<script src="{% static 'assets/js/app.js' %}"></script>
<script src="{% static 'global_assets/js/demo_pages/dashboard.js' %}"></script>
<script src="{% static 'global_assets/js/demo_pages/layout_navbar_secondary_fixed.js' %}"></script>
<!-- /theme JS files -->

<!-- Footer -->
<div class="footer text-muted">
    &copy; 2015. <a href="#">Limitless Web App Kit</a> by <a href="http://themeforest.net/user/Kopyov"
        target="_blank">Eugene Kopyov</a>
</div>
<!-- /footer -->

</body>

</html>

{% include 'dashboards/landing/qk_stats.html' %}

{% if cl.client_id == income_classifier_prediction|get_item:"cust_id" %}

<span class="badge bg-blue">
    {{income_classifier_prediction|get_item:"status"}}
</span>
{% endif %}

templates/account_base/header.html
<!-- set bodyTheme = "u-card-v1" -->
{% load static %}
{% include 'account/base/main_nav.html' %}

templates/account_base/main_nav.html
{% load static %}
<!-- Main navbar -->
<div class="navbar navbar-inverse">
    <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'account:index'%}?next={{'/'}}"><img
                src="{% static 'global_assets/images/dlogo.png' %}" alt=""></a>

        <ul class="nav navbar-nav pull-right visible-xs-block">
            <li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
        </ul>
    </div>

    <div class="navbar-collapse collapse" id="navbar-mobile">
        <ul class="nav navbar-nav navbar-right">
            <!-- <li>
                <a href="http://financial-paradise.com/admin">
                    <span class="">
                        admin login</span>
                </a>
            </li>

            <li>
                <a href="{% url 'account:login'%}?next={{'/'}}">
                    <span>
                        officer login</span>
                </a>
            </li> -->
            <!-- 
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown">
                    <i class="icon-cog3"></i>
                    <span class="visible-xs-inline-block position-right"> Options</span>
                </a>
            </li> -->
        </ul>
    </div>
</div>
<!-- /main navbar -->

templates/account_base/secondary_nav.html
{% load static %}

<!-- Secondary navbar -->
<div class="navbar navbar-expand-md navbar-light navbar-sticky">
    <div class="text-center d-md-none w-100">
        <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse"
            data-target="#navbar-navigation">
            <i class="icon-unfold mr-2"></i>
            Navigation
        </button>
    </div>

    <div class="navbar-collapse collapse" id="navbar-navigation">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="{% url 'companies:index' %}" class="navbar-nav-link active">
                    <i class="icon-home4 mr-2"></i>
                    Home
                </a>
            </li>

            <li class="nav-item nav-item-levels mega-menu-full">
                <a href="{% url 'companies:application_analytics' %}" class="navbar-nav-link">
                    <i class="icon-make-group mr-2"></i>
                    Application Scoring Predictions
                </a>
            </li>

            <li class="nav-item dropdown">
                <a href="{% url 'companies:application_analytics' %}" class="navbar-nav-link">
                    <i class="icon-strategy mr-2"></i>
                    Behavioral Scoring Predictions
                </a>
            </li>
            <li class="nav-item dropdown">
                <a href="{% url 'companies:application_analytics' %}" class="navbar-nav-link">
                    <i class="icon-alignment-unalign mr-2"></i>
                    Retention Scoring Predictions
                </a>
            </li>
            <li class="nav-item dropdown">
                <a href="{% url 'companies:application_analytics' %}" class="navbar-nav-link">
                    <i class="icon-file-text2 mr-2"></i>
                    Reports
                </a>
            </li>
            <!-- <li class="nav-item dropdown">
                <a href="{% url 'companies:income_classifier' %}" class="navbar-nav-link">
                    <i class="icon-file-text2 mr-2"></i>
                    income_classifier_prediction
                </a>
            </li> -->
        </ul>

        <ul class="navbar-nav ml-md-auto">
            <li class="nav-item dropdown">
                <a href="#" class="navbar-nav-link dropdown-toggle" data-toggle="dropdown">
                    <i class="icon-gear mr-2"></i>
                    Connect
                </a>

                <div class="dropdown-menu dropdown-menu-right dropdown-content wmin-md-350">
                    <div class="dropdown-content-body p-2">
                        <div class="row no-gutters">
                            <div class="col-12 col-sm-4">
                                <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                    <i class="icon-github4 icon-2x"></i>
                                    <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Github</div>
                                </a>

                                <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                    <i class="icon-dropbox text-blue-400 icon-2x"></i>
                                    <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Dropbox</div>
                                </a>
                            </div>

                            <div class="col-12 col-sm-4">
                                <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                    <i class="icon-dribbble3 text-pink-400 icon-2x"></i>
                                    <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Dribbble</div>
                                </a>

                                <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                    <i class="icon-google-drive text-success-400 icon-2x"></i>
                                    <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Drive</div>
                                </a>
                            </div>

                            <div class="col-12 col-sm-4">
                                <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                    <i class="icon-twitter text-info-400 icon-2x"></i>
                                    <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Twitter</div>
                                </a>

                                <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                    <i class="icon-youtube text-danger icon-2x"></i>
                                    <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Youtube</div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a href="#" class="navbar-nav-link dropdown-toggle" data-toggle="dropdown">
                    <i class="icon-cog3"></i>
                    <span class="d-md-none ml-2">Settings</span>
                </a>

                <div class="dropdown-menu dropdown-menu-right">
                    <a href="#" class="dropdown-item"><i class="icon-user-lock"></i> Account security</a>
                    <a href="#" class="dropdown-item"><i class="icon-statistics"></i> Analytics</a>
                    <a href="#" class="dropdown-item"><i class="icon-accessibility"></i> Accessibility</a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item"><i class="icon-gear"></i> All settings</a>
                </div>
            </li>
        </ul>
    </div>
</div>
<!-- /secondary navbar -->