account/urls.py
from django.conf.urls import url
from django.urls import path, include
from .views import register, view_client,login, activate, account_activation_sent, logout, index,home

# SET THE NAMESPACE!
app_name = 'account'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('login/', login, name='login'),
    path('index/', index, name='index'),
    path('home/', home, name='home'),
    path('<int:loan_id>view_client/', view_client, name='view_client'),
    url(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
]

companies/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views 
# from .views import *
# SET THE NAMESPACE!
app_name = 'companies'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    # path("loan_history_listing/", views.Loan_HistoryListing.as_view(), name = 'listing'),
    url(r'^api/v1.0/application_scoring[/]?$', views.ApplicationAPIView.as_view(), name='application_scoring_view'),
    url(r'^api/v1.0/behavioral_scoring[/]?$', views.BehavioralAPIView.as_view(), name='behavioral_scoring_view'),
    url(r'^api/v1.0/retention_scoring[/]?$', views.RetentionAPIView.as_view(), name='retention_scoring_view'),
    path("ajax/business/", views.getBusiness, name = 'get_businesses'),
    path("ajax/mortage/", views.getMortage, name = 'get_mortages'),
    path("ajax/school/", views.getSchool, name = 'get_schools'),
    path("ajax/funeral/", views.getFuneral, name = 'get_funerals'),
    path('data_for_charts', views.data_for_charts, name="data_for_charts"),
    path('data_aggretation', views.data_aggretation, name="data_aggretation"),
    path('<int:loan_id>/application_report_export_csv/$', views.application_report_export_csv, name="application_report_export_csv"),
    path('<int:loan_id>/application_report/$', views.application_report, name="application_report"),
    path('index/$', views.HomeView.as_view(), name="index"),    
    # path('', views.HomeView.as_view(), name="index"), 
    url(
        r"^index/(?P<user_id>.+)", views.HomeView.as_view(), name="index"
    ),

    path('income_classifier/', views.ApplicationAnalyticsResultsView.as_view(), name="income_classifier"),    
    path('application_analytics/', views.ApplicationAnalyticsResultsView.as_view(), name='application_analytics'),
    path('retention_analytics/', views.RetentionAnalyticsResultsView.as_view(), name='retention_analytics'),
    path('behavioral_analytics/', views.BehavioralAnalyticsResultsView.as_view(), name='behavioral_analytics'),
    path('client_profile/', views.client_profile, name='client_profile'),
    path('application_report/', views.application_report, name='application_report'),
    path('application_report_export_csv/', views.application_report_export_csv, name='application_report_export_csv'),
    path('officer_profile/', views.officer_profile, name='officer_profile'),
    path('live_app_score_pred/', views.live_app_score_pred, name='live_app_score_pred'),

    path('reports/', views.reports, name='reports'),
    path('articles/', views.articles, name='articles'),
   
]

fintechapp/urls.py
# backend/server/server/urls.py file
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from account.views import home
from companies import views
from apps.endpoints.urls import urlpatterns as endpoints_urlpatterns
urlpatterns = [
    path('', home, name='home'),
    path('companies_home_dash', views.HomeView.as_view(), name="companies_home_dash"),
    path('admin/', admin.site.urls),
    path('companies/', include('companies.urls')),
    path('d_processor/', include('d_processor.urls')),
    path('account/', include('account.urls')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
]

urlpatterns += endpoints_urlpatterns
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/dashboards/landing/chartsjs.html
{% load static %}
<div id="container" style="width: 75%;">
    <canvas id="population-chart" data-url="{% url 'business:data_aggretation' %}"></canvas>
</div>
<!-- Core JS files -->

<script src="{% static 'account/global_assets/js/main/jquery.min.js' %}"></script>
<script src="{% static 'account/assets/js/chart.bundle.js' %}"></script>
<script>
    $(function () {

        var $populationChart = $("#population-chart");
        $.ajax({
            url: $populationChart.data("url"),
            success: function (data) {

                var ctx = $populationChart[0].getContext("2d");

                new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: data.labels,
                        datasets: [{
                            label: 'Population',
                            backgroundColor: 'blue',
                            data: data.data
                        }]
                    },
                    options: {
                        responsive: true,
                        legend: {
                            position: 'top',
                        },
                        title: {
                            display: true,
                            text: 'Population Bar Chart'
                        }
                    }
                });

            }
        });

    });
</script>

templates/dashboards/landing/index.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

{% include 'dashboards/global/page.header.html' %}
<!-- Page container -->
<div class="page-container">

  <!-- Page content -->
  <div class="page-content">

    <!-- Main content -->
    <div class="content-wrapper">

      <!-- Content area -->
      <div class="content">
        <div class="row">
          <div class="col-lg-8">

            {% include 'dashboards/landing/qk_stats.html' %}
            {% include 'dashboards/landing/kpi_summary.html' %}
          </div>
          <div class="col-lg-4">

            {% include 'dashboards/landing/messages.html' %}

          </div>
        </div>

      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/dashboards/landing/qk_stats.html
{% load static %}

<!-- Quick stats boxes -->
<div class="row">
    <div class="col-lg-4">

        <!-- Members online -->
        <div class="panel ">
            <div class="panel-body">
                <div class="heading-elements">
                    <span class="heading-text badge bg-teal-800">+{{ webdata.1.grade_a.1 }}%</span>
                </div>

                <div id="chartjs1">
                    <canvas id="data_aggretation" width="400px" height="400px"
                        data-url="{% url 'companies:data_aggretation' %}"></canvas>

                </div>
            </div>
        </div>
        <!-- /members online -->


    </div>

    <div class="col-lg-4">

        <!-- Members online -->
        <div class="panel ">
            <div class="panel-body">
                <div class="heading-elements">
                    <span class="heading-text badge bg-teal-800">+{{ webdata.1.grade_a.1 }}%</span>
                </div>
                <div id="chartjs2">
                    <canvas id="data_aggretation2" width="500px" height="500px"
                        data-url="{% url 'companies:data_aggretation' %}"></canvas>
                </div>
            </div>
        </div>
        <!-- /members online -->

    </div>

    <div class="col-lg-4">

        <!-- Members online -->
        <div class="panel ">
            <div class="panel-body">
                <div class="heading-elements">
                    <span class="heading-text badge bg-teal-800">+{{ webdata.1.grade_a.1 }}%</span>
                </div>
                <div id="chartjs3">
                    <canvas id="data_aggretation3" width="200px" height="200px"
                        data-url="{% url 'companies:data_aggretation' %}"></canvas>
                </div>
            </div>
        </div>
        <!-- /members online -->
    </div>
</div>
<!-- /quick stats boxes -->

<!-- Core JS files -->
<script src="{% static 'global_assets/js/main/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/chart.bundle.js' %}"></script>
<script>

    $(function () {

        var $data_aggretationChart = $("#data_aggretation");
        $.ajax({
            url: $data_aggretationChart.data("url"),
            success: function (data) {

                var ctx = $data_aggretationChart[0].getContext("2d");

                new Chart(ctx, {
                    type: 'doughnut',
                    data: {
                        labels: data.labels,
                        datasets: [{
                            label: 'Occupation',
                            backgroundColor: [
                                'rgba(255, 99, 132, 0.2)',
                                'rgba(54, 162, 235, 0.2)',
                                'rgba(255, 206, 86, 0.2)',
                                'rgba(75, 192, 192, 0.2)',
                                'rgba(153, 102, 255, 0.2)',
                                'rgba(255, 159, 64, 0.2)'
                            ],

                            data: data.data
                        }]
                    },
                    options: {
                        responsive: true,
                        legend: {
                            position: 'bottom',
                            display: false,
                        },
                        title: {
                            display: true,
                            text: 'KPI'
                        }
                    }
                });

            }
        });

    });

</script>

<script>

    $(function () {

        var $data_aggretationChart = $("#data_aggretation2");
        $.ajax({
            url: $data_aggretationChart.data("url"),
            success: function (data) {

                var ctx = $data_aggretationChart[0].getContext("2d");

                new Chart(ctx, {
                    type: 'doughnut',
                    data: {
                        labels: data.labels,
                        datasets: [{
                            label: 'Occupation',
                            backgroundColor: [
                                'rgba(255, 99, 132, 0.2)',
                                'rgba(54, 162, 235, 0.2)',
                                'rgba(255, 206, 86, 0.2)',
                                'rgba(75, 192, 192, 0.2)',
                                'rgba(153, 102, 255, 0.2)',
                                'rgba(255, 159, 64, 0.2)'
                            ],
                            data: data.data
                        }]
                    },
                    options: {
                        responsive: true,
                        legend: {
                            display: false,
                            position: 'top',
                        },
                        title: {
                            display: true,
                            text: 'KPI'
                        }
                    }
                });

            }
        });

    });

</script>

<script>

    $(function () {

        var $data_aggretationChart = $("#data_aggretation3");
        $.ajax({
            url: $data_aggretationChart.data("url"),
            success: function (data) {

                var ctx = $data_aggretationChart[0].getContext("2d");

                new Chart(ctx, {
                    type: 'pie',
                    data: {
                        labels: data.labels,
                        datasets: [{
                            label: 'Occupation',
                            backgroundColor: [
                                'rgba(255, 99, 132, 0.2)',
                                'rgba(54, 162, 235, 0.2)',
                                'rgba(255, 206, 86, 0.2)',
                                'rgba(75, 192, 192, 0.2)',
                                'rgba(153, 102, 255, 0.2)',
                                'rgba(255, 159, 64, 0.2)'
                            ],
                            data: data.data
                        }]
                    },
                    options: {
                        responsive: true,
                        legend: {
                            display: false,
                            position: 'top',
                        },
                        title: {
                            display: true,
                            text: 'KPI'
                        }
                    }
                });

            }
        });

    });

</script>

templates/dashboards/landing/table.html
{% load static %}

<!-- Individual column searching (selects) -->
<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">Individual column searching</h5>
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
                <li><a data-action="reload"></a></li>
                <li><a data-action="close"></a></li>
            </ul>
        </div>
    </div>

    <div class="panel-body">
    </div>

    <table class="table table-sm" id="list_data" data-toggle="table" url="{% url 'companies:get_predictions' %}">
        <thead>
            <tr>
                <th>Loan ID</th>

                <th>Colleteral</th>
                <th>Amount Applied For</th>
                <th>Social Media Assessment</th>
                <th>Credit History Assessment</th>
                <th>Pyschometric Assessment</th>
                <th>Text Assessment Analytics</th>
                <th>Overal Assessment</th>
                <th>Decision</th>
                <th><i class="icon-arrow-down12"></i></th>


            </tr>
        </thead>
        <tbody>
            {% for cl in loan %}
            <tr>
                <td>{{cl.LOAN_ID}}</td>

                <td><a href="#">{{cl.colleteral}}</a></td>
                <td><span class="label label-danger ">${{ cl.AMT_CREDIT }}</span></td>
                {% for d_id, d_info in predict_dict_data.items  %}

                {% if d_id == cl.LOAN_ID   %}
                {% for l in d_info %}
                <td class="bg-{{l.color}}" style="text-overflow: clip;">
                    <span class=''>
                        {{l.text}}
                    </span>

                </td>
                {% endfor %}
                {% endif  %}
                {% endfor %}


                {% for d_id, d_info in predict_dict_data.items  %}
                {% if d_id == cl.LOAN_ID   %}
                {% for l in d_info %}
                <td class="bg-{{l.color}}" style="text-overflow: clip;">
                    <span class=''>
                        {{l.text}}
                    </span>

                </td>
                {% endfor %}
                {% endif  %}
                {% endfor %}
                {% for d_id, d_info in predict_dict_data.items  %}

                {% if d_id == cl.LOAN_ID   %}
                {% for l in d_info %}
                <td class="bg-{{l.color}}" style="text-overflow: clip;">
                    <span class=''>
                        {{l.text}}
                    </span>

                </td>
                {% endfor %}
                {% endif  %}
                {% endfor %}


                {% for d_id, d_info in predict_dict_data.items  %}
                {% if d_id == cl.LOAN_ID   %}
                {% for l in d_info %}
                <td class="bg-{{l.color}}" style="text-overflow: clip;">
                    <span class=''>
                        {{l.text}}
                    </span>

                </td>
                {% endfor %}
                {% endif  %}
                {% endfor %}

                {% for d_id, d_info in predict_dict_data.items  %}

                {% if d_id == cl.LOAN_ID   %}
                {% for l in d_info %}
                <td class="bg-{{l.color}}" style="text-overflow: clip;">
                    <span class=''>
                        {{l.text}}
                    </span>

                </td>
                {% endfor %}
                {% endif  %}
                {% endfor %}


                {% for d_id, d_info in predict_dict_data.items  %}
                {% if d_id == cl.LOAN_ID   %}
                {% for l in d_info %}
                <td class="bg-{{l.color}}" style="text-overflow: clip;">
                    <span class=''>
                        {{l.text}}
                    </span>

                </td>
                {% endfor %}
                {% endif  %}
                {% endfor %}
                <td class="text-center">
                    <ul class="icons-list">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="icon-menu9"></i>
                            </a>

                            <ul class="dropdown-menu dropdown-menu-right">
                                <li><a href="{% url 'account:view_client' cl.LOAN_ID %}"><i class="icon-person"></i>
                                        View
                                        Client</a></li>
                                <li><a href="{% url 'companies:application_report' cl.LOAN_ID %}"><i
                                            class="icon-book"></i> View
                                        Report</a></li>
                                <li><a href="{% url 'companies:application_report_export_csv' cl.LOAN_ID %}"><i
                                            class="icon-file-excel"></i> Export to .csv</a></li>
                            </ul>
                        </li>
                    </ul>
                </td>
            </tr>
            {% endfor %}

        </tbody>
        </tbody>
    </table>
</div>
<!-- /individual column searching (selects) -->
<script src="{% static 'global_assets/js/main/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/chart.bundle.js' %}"></script>
<!-- <script>

    $(function () {

        let url = $('#list_data').attr("url")
        $.ajax({
            url: url,
            success: function (data) {

                $.each(data, function (a, b) {
                    /// do stuff
                    row = "<tr> <td>" + b.probability + "</td>" +
                        "<td>" + b.probability + "</td>" +
                        "<td>" + b.probability + "</td>" +
                        "<td>" + b.probability + "</td>" +
                        "<td>" + b.probability + "</td>" +
                        "<td>" + b.probability + "</td></tr>"

                    $("#listing").append(row);
                });

            }
        });

    });

</script> -->


<script>
    var frm = $('#filterForm');
    frm.submit(getAjax);
    function getAjax() {
        var formData = JSON.stringify($("#filterForm").serializeArray());
        console.log("Request parameters:")
        console.log(JSON.parse(formData))
        $.ajax({
            headers: { "X-CSRFToken": '{{csrf_token}}' },
            type: "POST",
            url: "{% url 'companies:get_predictions' %}",
            contentType: 'application/json',
            dataType: 'json',
            data: formData,
            success: function (data) {
                jsonData = console.log(data);
                var dataObj = JSON.parse(data);
                console.log("Response data:")
                console.log(dataObj)
                $.each(data, function (a, b) {
                    alert("We got what we came for!" + b.probability);
                    /// do stuff
                    row = "<tr> <td>" + b.probability + "</td>" +
                        "<td>" + b.probability + "</td>" +
                        "<td>" + b.probability + "</td>" +
                        "<td>" + b.probability + "</td>" +
                        "<td>" + b.probability + "</td>" +
                        "<td>" + b.probability + "</td></tr>"

                    $("#listing").append(row);
                });
                //more stuff here, too much for this example
            },
        }); return false;
    }
</script>