account/urls.py
from django.conf.urls import url
from django.urls import path, include
from .views import register, view_client,login, activate, account_activation_sent, logout, index,home

# SET THE NAMESPACE!
app_name = 'account'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('login/', login, name='login'),
    path('index/', index, name='index'),
    path('home/', home, name='home'),
    path('<int:loan_id>view_client/', view_client, name='view_client'),
    url(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
]

companies/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views 
# from .views import *
# SET THE NAMESPACE!
app_name = 'companies'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    # path("loan_history_listing/", views.Loan_HistoryListing.as_view(), name = 'listing'),
    url(r'^api/v1.0/application_scoring[/]?$', views.ApplicationAPIView.as_view(), name='application_scoring_view'),
    url(r'^api/v1.0/behavioral_scoring[/]?$', views.BehavioralAPIView.as_view(), name='behavioral_scoring_view'),
    url(r'^api/v1.0/retention_scoring[/]?$', views.RetentionAPIView.as_view(), name='retention_scoring_view'),
    path("ajax/business/", views.getBusiness, name = 'get_businesses'),
    path("ajax/mortage/", views.getMortage, name = 'get_mortages'),
    path("ajax/school/", views.getSchool, name = 'get_schools'),
    path("ajax/funeral/", views.getFuneral, name = 'get_funerals'),
    path('data_for_charts', views.data_for_charts, name="data_for_charts"),
    path('data_aggretation', views.data_aggretation, name="data_aggretation"),
    path('<int:loan_id>/application_report_export_csv/$', views.application_report_export_csv, name="application_report_export_csv"),
    path('<int:loan_id>/application_report/$', views.application_report, name="application_report"),
    path('index/$', views.HomeView.as_view(), name="index"),    
    # path('', views.HomeView.as_view(), name="index"), 
    url(
        r"^index/(?P<user_id>.+)", views.HomeView.as_view(), name="index"
    ),

    path('income_classifier/', views.ApplicationAnalyticsResultsView.as_view(), name="income_classifier"),    
    path('application_analytics/', views.ApplicationAnalyticsResultsView.as_view(), name='application_analytics'),
    path('retention_analytics/', views.RetentionAnalyticsResultsView.as_view(), name='retention_analytics'),
    path('behavioral_analytics/', views.BehavioralAnalyticsResultsView.as_view(), name='behavioral_analytics'),
    path('client_profile/', views.client_profile, name='client_profile'),
    path('application_report/', views.application_report, name='application_report'),
    path('application_report_export_csv/', views.application_report_export_csv, name='application_report_export_csv'),
    path('officer_profile/', views.officer_profile, name='officer_profile'),
    path('live_app_score_pred/', views.live_app_score_pred, name='live_app_score_pred'),

    path('reports/', views.reports, name='reports'),
    path('articles/', views.articles, name='articles'),
   
]

fintechapp/urls.py
# backend/server/server/urls.py file
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from account.views import home
from companies import views
from apps.endpoints.urls import urlpatterns as endpoints_urlpatterns
urlpatterns = [
    path('', home, name='home'),
    path('companies_home_dash', views.HomeView.as_view(), name="companies_home_dash"),
    path('admin/', admin.site.urls),
    path('companies/', include('companies.urls')),
    path('d_processor/', include('d_processor.urls')),
    path('account/', include('account.urls')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
]

urlpatterns += endpoints_urlpatterns
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/dashboards/filters.html
<section class="site_filter">
    <div class="container-fluid">
        <div class="row">
            {% if user.role == 'manager' %}
            <div class="col-sm-2 col-2">
                <div class="form-group">
                    <label for="country">loan officer</label>
                    <select class="form-control" id="business" url="{%url 'companies:get_businesses' %}">
                    </select>
                </div>
            </div>
            {% endif %}
            <div class="col-sm-2 col-2">
                <div class="form-group">
                    <label for="office">loan officere</label>
                    <select class="form-control" id="business" url="{%url 'companies:get_businesses' %}">
                    </select>
                </div>
            </div>
            <div class="col-sm-2 col-2">
                <div class="form-group">
                    <label for="mortage">Client class </label>
                    <select class="form-control" id="mortage" url="{%url 'companies:get_mortages' %}">
                    </select>
                </div>
            </div>
            <div class="col-sm-2 col-2">
                <div class="form-group">
                    <label for="funeral">Risk Level</label>
                    <select class="form-control" id="funeral" url="{%url 'companies:get_funerals' %}">
                        <option value='all' selected>All risk</option>
                    </select>
                </div>
            </div>
            <!-- <div class="col-sm-2 col-2">
                <div class="form-group">
                    <label for="school">school</label>
                    <select class="form-control" id="school" url="{%url 'companies:get_schools' %}">
                        <option value='all' selected>All schools</option>
                    </select>
                </div>
            </div> -->
            <div class="col-sm-2 col-2">
                <div class="form-group">
                    <label for="Province">Sort By</label>
                    <select class="form-control" id="sort_by">
                        <option selected="true" disabled="disabled" value="none">Choose option</option>
                        <option value='income'>Income</option>
                        <option value='credit_amount'>Credit amount</option>
                    </select>
                </div>
            </div>
            <div class="col-sm-2 col-2">
                <div class="row justify-content-center align-self-center" style="color:white; margin-top:30px;">
                    <a class="btn btn-secondary" id="display_all">Display all</a>
                </div>
            </div>
        </div>
    </div>
</section>
<br />