account/urls.py
from django.conf.urls import url
from django.urls import path, include
from .views import register, view_client,login, activate, account_activation_sent, logout, index,home

# SET THE NAMESPACE!
app_name = 'account'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('login/', login, name='login'),
    path('index/', index, name='index'),
    path('home/', home, name='home'),
    path('<int:loan_id>view_client/', view_client, name='view_client'),
    url(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
]

companies/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views 
# from .views import *
# SET THE NAMESPACE!
app_name = 'companies'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    # path("loan_history_listing/", views.Loan_HistoryListing.as_view(), name = 'listing'),
    url(r'^api/v1.0/application_scoring[/]?$', views.ApplicationAPIView.as_view(), name='application_scoring_view'),
    url(r'^api/v1.0/behavioral_scoring[/]?$', views.BehavioralAPIView.as_view(), name='behavioral_scoring_view'),
    url(r'^api/v1.0/retention_scoring[/]?$', views.RetentionAPIView.as_view(), name='retention_scoring_view'),
    path("ajax/business/", views.getBusiness, name = 'get_businesses'),
    path("ajax/mortage/", views.getMortage, name = 'get_mortages'),
    path("ajax/school/", views.getSchool, name = 'get_schools'),
    path("ajax/funeral/", views.getFuneral, name = 'get_funerals'),
    path('data_for_charts', views.data_for_charts, name="data_for_charts"),
    path('data_aggretation', views.data_aggretation, name="data_aggretation"),
    path('<int:loan_id>/application_report_export_csv/$', views.application_report_export_csv, name="application_report_export_csv"),
    path('<int:loan_id>/application_report/$', views.application_report, name="application_report"),
    path('index/$', views.HomeView.as_view(), name="index"),    
    # path('', views.HomeView.as_view(), name="index"), 
    url(
        r"^index/(?P<user_id>.+)", views.HomeView.as_view(), name="index"
    ),

    path('income_classifier/', views.ApplicationAnalyticsResultsView.as_view(), name="income_classifier"),    
    path('application_analytics/', views.ApplicationAnalyticsResultsView.as_view(), name='application_analytics'),
    path('retention_analytics/', views.RetentionAnalyticsResultsView.as_view(), name='retention_analytics'),
    path('behavioral_analytics/', views.BehavioralAnalyticsResultsView.as_view(), name='behavioral_analytics'),
    path('client_profile/', views.client_profile, name='client_profile'),
    path('application_report/', views.application_report, name='application_report'),
    path('application_report_export_csv/', views.application_report_export_csv, name='application_report_export_csv'),
    path('officer_profile/', views.officer_profile, name='officer_profile'),
    path('live_app_score_pred/', views.live_app_score_pred, name='live_app_score_pred'),

    path('reports/', views.reports, name='reports'),
    path('articles/', views.articles, name='articles'),
   
]

fintechapp/urls.py
# backend/server/server/urls.py file
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from account.views import home
from companies import views
from apps.endpoints.urls import urlpatterns as endpoints_urlpatterns
urlpatterns = [
    path('', home, name='home'),
    path('companies_home_dash', views.HomeView.as_view(), name="companies_home_dash"),
    path('admin/', admin.site.urls),
    path('companies/', include('companies.urls')),
    path('d_processor/', include('d_processor.urls')),
    path('account/', include('account.urls')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
]

urlpatterns += endpoints_urlpatterns
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/dashboards/application/chartsjs.html
{% load static %}
<div style="width: 200px; margin-top: 20%;" id="chartjs1">
    Chart Data {{ webdata.1.grade_a.1 }}
    <canvas id="chart1" width="200px" height="200px"></canvas>
</div>
<!-- Core JS files -->
<script src="{% static 'assets/js/chart.bundle.js' %}"></script>
<script>
    var ctx = document.getElementById("chart1").getContext('2d');
    my_chart = new Chart(ctx, {
        type: 'pie',
        data: {
            labels: ['Female', 'Male'],
            datasets: [{
                label: 'Gender vs Loan Volume',
                data: [{{ webdata.1.grade_a.1 }}, {{ webdata.1.grade_b.1 }}],
        backgroundColor: [
            'rgba(255, 99, 132, 0.2)',
            'rgba(54, 162, 235, 0.2)',
            'rgba(255, 206, 86, 0.2)',
            'rgba(75, 192, 192, 0.2)',
            'rgba(153, 102, 255, 0.2)',

        ],
        borderColor: [
            'rgba(255, 99, 132, 1)',
            'rgba(54, 162, 235, 1)',
            'rgba(255, 206, 86, 1)',
            'rgba(75, 192, 192, 1)',
            'rgba(153, 102, 255, 1)',


        ],
        borderWidth: 1

    }]
       },

        options: {
        scales: {
            yAxis: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }

   })
</script>

templates/dashboards/application/datatable_api.html
{% load static %}
{% load custom_tags %}
<!-- Individual column searching (selects) -->
<div class="panel panel-flat">
    <div class="panel-heading">
        <!-- <h5 class="panel-title">Individual column searching</h5> -->
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
                <li><a data-action="reload"></a></li>
                <li><a data-action="close"></a></li>
            </ul>
        </div>
    </div>

    <div class="panel-body">
        {% include 'dashboards/filters.html' %}
        <div class="row justify-content-center">
            <nav aria-label="navigation">
                <ul class="pagination">
                    <li style="margin: 5px;" class="page-item">
                        <button class="btn btn-primary page-link" id="previous">Previous</button>
                    </li>
                    <li style="padding-right: 15px;" class="page-item pull-right">
                        <button class="btn btn-primary page-link" id="next">Next</button>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

    <table width="100%" class="table table-striped" id="list_data" data-toggle="table"
        url="{% url 'companies:listing' %}">
        <thead>
            <tr>
                <th>Loan Officer</th>
                <th>Client Name</th>
                <th>Age</th>
                <th>Colleteral</th>
                <th>Amount Applied For</th>
                <th>Social Media Assessment</th>
                <th>Credit History Assessment</th>
                <th>Pyschometric Assessment</th>
                <th>Text Assessment Analytics</th>
                <th>Overal Assessment</th>
                <th>Decision</th>
                <th class="text-center">Actions</th>
            </tr>
        </thead>
        <div id="no_results">
            <h5>No results found</h5>
        </div>
        <tbody id="listing">
        </tbody>

    </table>

</div>
<!-- /individual column searching (selects) -->
{% block script %}
<script src="{% static 'account/global_assets/js/main/jquery.min.js' %}"></script>
<script src="{% static 'account/assets/js/filters.js' %}" type="text/javascript">
</script>
{% endblock %}

templates/dashboards/application/index.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

{% include 'dashboards/global/page.header.html' %}
<!-- Page container -->
<div class="page-container">

  <!-- Page content -->
  <div class="page-content">

    <!-- Main content -->
    <div class="content-wrapper">

      <!-- Content area -->
      <div class="content">
        <div class="row">


          {% include 'dashboards/application/qk_stats.html' %}
          {% include 'dashboards/application/table.html' %}


        </div>

      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/dashboards/application/kpi_summary.html
<div class="card-header header-elements-sm-inline">
    <h6 class="card-title">Marketing test</h6>
    <div class="header-elements">
        <span class="badge bg-success badge-pill">28 active</span>
        <div class="list-icons ml-3">
            <div class="list-icons-item dropdown">
                <a href="#" class="list-icons-item dropdown-toggle" data-toggle="dropdown"><i
                        class="icon-menu7"></i></a>
                <div class="dropdown-menu">
                    <a href="#" class="dropdown-item"><i class="icon-sync"></i> Update
                        data</a>
                    <a href="#" class="dropdown-item"><i class="icon-list-unordered"></i>
                        Detailed log</a>
                    <a href="#" class="dropdown-item"><i class="icon-pie5"></i>
                        Statistics</a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item"><i class="icon-cross3"></i> Clear
                        list</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="card-body d-sm-flex align-items-sm-center justify-content-sm-between flex-sm-wrap">
    <div class="d-flex align-items-center mb-3 mb-sm-0">
        <div id="campaigns-donut"></div>
        <div class="ml-3">
            <h5 class="font-weight-semibold mb-0">38,289 <span class="text-success font-size-sm font-weight-normal"><i
                        class="icon-arrow-up12"></i>
                    (+16.2%)</span></h5>
            <span class="badge badge-mark border-success mr-1"></span> <span class="text-muted">May 12, 12:30
                am</span>
        </div>
    </div>

    <div class="d-flex align-items-center mb-3 mb-sm-0">
        <div id="campaign-status-pie"></div>
        <div class="ml-3">
            <h5 class="font-weight-semibold mb-0">2,458 <span class="text-danger font-size-sm font-weight-normal"><i
                        class="icon-arrow-down12"></i>
                    (-4.9%)</span></h5>
            <span class="badge badge-mark border-danger mr-1"></span> <span class="text-muted">Jun 4, 4:00
                am</span>
        </div>
    </div>

    <div>
        <a href="#" class="btn bg-indigo-300"><i class="icon-statistics mr-2"></i> View
            report</a>
    </div>
</div>

templates/dashboards/application/qk_stats.html
{% load static %}

<!-- Quick stats boxes -->
<div class="row">
    <div class="col-lg-3">

        <!-- Members online -->
        <div class="panel ">
            <div class="panel-body">
                <div class="heading-elements">
                    <span class="heading-text badge bg-teal-800">+{{ webdata.1.grade_a.1 }}%</span>
                </div>

                <div id="chartjs1">
                    <canvas id="data_aggretation01" width="200px" height="200px"
                        data-url="{% url 'companies:data_aggretation' %}"></canvas>

                </div>
            </div>
        </div>
        <!-- /members online -->


    </div>

    <div class="col-lg-3">

        <!-- Members online -->
        <div class="panel ">
            <div class="panel-body">
                <div class="heading-elements">
                    <span class="heading-text badge bg-teal-800">+{{ webdata.1.grade_a.1 }}%</span>
                </div>
                <div id="chartjs2">
                    <canvas id="data_aggretation02" width="200px" height="200px"
                        data-url="{% url 'companies:data_aggretation' %}"></canvas>
                </div>
            </div>
        </div>
        <!-- /members online -->

    </div>

    <div class="col-lg-3">

        <!-- Members online -->
        <div class="panel ">
            <div class="panel-body">
                <div class="heading-elements">
                    <span class="heading-text badge bg-teal-800">+{{ webdata.1.grade_a.1 }}%</span>
                </div>
                <div id="chartjs3">
                    <canvas id="data_aggretation03" width="200px" height="200px"
                        data-url="{% url 'companies:data_aggretation' %}"></canvas>
                </div>
            </div>
        </div>
        <!-- /members online -->
    </div>
</div>
<!-- /quick stats boxes -->
</div>
<!-- /quick stats boxes -->

<!-- Core JS files -->
<script src="{% static 'global_assets/js/main/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/chart.bundle.js' %}"></script>
<script>

    $(function () {

        var $data_aggretationChart = $("#data_aggretation01");
        $.ajax({
            url: $data_aggretationChart.data("url"),
            success: function (data) {

                var ctx = $data_aggretationChart[0].getContext("2d");

                new Chart(ctx, {
                    type: 'doughnut',
                    data: {
                        labels: data.labels,
                        datasets: [{
                            label: 'Occupation',
                            backgroundColor: [
                                'rgba(255, 99, 132, 0.2)',
                                'rgba(54, 162, 235, 0.2)',
                                'rgba(255, 206, 86, 0.2)',
                                'rgba(75, 192, 192, 0.2)',
                                'rgba(153, 102, 255, 0.2)',
                                'rgba(255, 159, 64, 0.2)'
                            ],

                            data: data.data
                        }]
                    },
                    options: {
                        responsive: true,
                        legend: {
                            display: false,
                            position: 'top',
                        },
                        title: {
                            display: true,
                            text: 'KPI'
                        }
                    }
                });

            }
        });

    });


    $(function () {

        var $data_aggretationChart = $("#data_aggretation02");
        $.ajax({
            url: $data_aggretationChart.data("url"),
            success: function (data) {

                var ctx = $data_aggretationChart[0].getContext("2d");

                new Chart(ctx, {
                    type: 'doughnut',
                    data: {
                        labels: data.labels,
                        datasets: [{
                            label: 'Occupation',
                            backgroundColor: [
                                'rgba(255, 99, 132, 0.2)',
                                'rgba(54, 162, 235, 0.2)',
                                'rgba(255, 206, 86, 0.2)',
                                'rgba(75, 192, 192, 0.2)',
                                'rgba(153, 102, 255, 0.2)',
                                'rgba(255, 159, 64, 0.2)'
                            ],

                            data: data.data
                        }]
                    },
                    options: {
                        responsive: true,
                        legend: {
                            display: false,
                            position: 'top',
                        },
                        title: {
                            display: true,
                            text: 'KPI'
                        }
                    }
                });

            }
        });

    });



    $(function () {

        var $data_aggretationChart = $("#data_aggretation03");
        $.ajax({
            url: $data_aggretationChart.data("url"),
            success: function (data) {

                var ctx = $data_aggretationChart[0].getContext("2d");

                new Chart(ctx, {
                    type: 'doughnut',
                    data: {
                        labels: data.labels,
                        datasets: [{
                            label: 'Occupation',
                            backgroundColor: [
                                'rgba(255, 99, 132, 0.2)',
                                'rgba(54, 162, 235, 0.2)',
                                'rgba(255, 206, 86, 0.2)',
                                'rgba(75, 192, 192, 0.2)',
                                'rgba(153, 102, 255, 0.2)',
                                'rgba(255, 159, 64, 0.2)'
                            ],

                            data: data.data
                        }]
                    },
                    options: {
                        responsive: true,
                        legend: {
                            display: false,
                            position: 'top',
                        },
                        title: {
                            display: true,
                            text: 'KPI'
                        }
                    }
                });

            }
        });

    });

    $(function () {

        var $data_aggretationChart = $("#data_aggretation");
        $.ajax({
            url: $data_aggretationChart.data("url"),
            success: function (data) {

                var ctx = $data_aggretationChart[0].getContext("2d");

                new Chart(ctx, {
                    type: 'doughnut',
                    data: {
                        labels: data.labels,
                        datasets: [{
                            label: 'Occupation',
                            backgroundColor: [
                                'rgba(255, 99, 132, 0.2)',
                                'rgba(54, 162, 235, 0.2)',
                                'rgba(255, 206, 86, 0.2)',
                                'rgba(75, 192, 192, 0.2)',
                                'rgba(153, 102, 255, 0.2)',
                                'rgba(255, 159, 64, 0.2)'
                            ],

                            data: data.data
                        }]
                    },
                    options: {
                        responsive: true,
                        legend: {
                            display: false,
                            position: 'top',
                        },
                        title: {
                            display: true,
                            text: 'KPI'
                        }
                    }
                });

            }
        });

    });

</script>

<script>

    $(function () {

        var $data_aggretationChart = $("#data_aggretation2");
        $.ajax({
            url: $data_aggretationChart.data("url"),
            success: function (data) {

                var ctx = $data_aggretationChart[0].getContext("2d");

                new Chart(ctx, {
                    type: 'line',
                    data: {
                        labels: data.labels,
                        datasets: [{
                            label: 'Occupation',
                            backgroundColor: [
                                'rgba(255, 99, 132, 0.2)',
                                'rgba(54, 162, 235, 0.2)',
                                'rgba(255, 206, 86, 0.2)',
                                'rgba(75, 192, 192, 0.2)',
                                'rgba(153, 102, 255, 0.2)',
                                'rgba(255, 159, 64, 0.2)'
                            ],
                            data: data.data
                        }]
                    },
                    options: {
                        responsive: true,
                        legend: {
                            display: false,
                            position: 'top',
                        },
                        title: {
                            display: true,
                            text: 'KPI'
                        }
                    }
                });

            }
        });

    });

</script>

<script>

    $(function () {

        var $data_aggretationChart = $("#data_aggretation3");
        $.ajax({
            url: $data_aggretationChart.data("url"),
            success: function (data) {

                var ctx = $data_aggretationChart[0].getContext("2d");

                new Chart(ctx, {
                    type: 'pie',
                    data: {
                        labels: data.labels,
                        datasets: [{
                            label: 'Occupation',
                            backgroundColor: [
                                'rgba(255, 99, 132, 0.2)',
                                'rgba(54, 162, 235, 0.2)',
                                'rgba(255, 206, 86, 0.2)',
                                'rgba(75, 192, 192, 0.2)',
                                'rgba(153, 102, 255, 0.2)',
                                'rgba(255, 159, 64, 0.2)'
                            ],
                            data: data.data
                        }]
                    },
                    options: {
                        responsive: true,
                        legend: {
                            display: false,
                            position: 'top',
                        },
                        title: {
                            display: true,
                            text: 'KPI'
                        }
                    }
                });

            }
        });

    });

</script>

templates/dashboards/application/support_stats.html
<!-- Support tickets -->
<div class="card">
    <div class="card-header header-elements-sm-inline">
        <h6 class="card-title">KPI summary Charts</h6>
        <div class="header-elements">
            <a class="text-default daterange-ranges font-weight-semibold cursor-pointer dropdown-toggle">
                <i class="icon-calendar3 mr-2"></i>
                <span></span>
            </a>
        </div>
    </div>

    <div class="card-body d-md-flex align-items-md-center justify-content-md-between flex-md-wrap">
        <div class="d-flex align-items-center mb-3 mb-md-0">
            <div id="campaigns-donut"></div>
            <div class="ml-3">
                <h5 class="font-weight-semibold mb-0">14,327 <span
                        class="text-success font-size-sm font-weight-normal"><i class="icon-arrow-up12"></i>
                        (+2.9%)</span></h5>
                <span class="badge badge-mark border-success mr-1"></span> <span class="text-muted">Jun 16, 10:00
                    am</span>
            </div>
        </div>

        <div class="d-flex align-items-center mb-3 mb-md-0">
            <div id="tickets-status"></div>
            <div class="ml-3">
                <h5 class="font-weight-semibold mb-0">14,327 <span
                        class="text-success font-size-sm font-weight-normal"><i class="icon-arrow-up12"></i>
                        (+2.9%)</span></h5>
                <span class="badge badge-mark border-success mr-1"></span> <span class="text-muted">Jun 16, 10:00
                    am</span>
            </div>
        </div>
        <div class="d-flex align-items-center mb-3 mb-md-0">
            <div id="campaign-status-pie"></div>
            <div class="ml-3">
                <h5 class="font-weight-semibold mb-0">14,327 <span
                        class="text-success font-size-sm font-weight-normal"><i class="icon-arrow-up12"></i>
                        (+2.9%)</span></h5>
                <span class="badge badge-mark border-success mr-1"></span> <span class="text-muted">Jun 16, 10:00
                    am</span>
            </div>
        </div>



    </div>
    <div class="card-body d-md-flex align-items-md-center justify-content-md-between flex-md-wrap">

        <div class="d-flex align-items-center mb-3 mb-md-0">
            <div id="campaign-status-pie3"></div>
            <div class="ml-3">
                <h5 class="font-weight-semibold mb-0">14,327 <span
                        class="text-success font-size-sm font-weight-normal"><i class="icon-arrow-up12"></i>
                        (+2.9%)</span></h5>
                <span class="badge badge-mark border-success mr-1"></span> <span class="text-muted">Jun 16, 10:00
                    am</span>
            </div>
        </div>
        <div class="d-flex align-items-center mb-3 mb-md-0">
            <div id="campaign-status-pie2"></div>
            <div class="ml-3">
                <h5 class="font-weight-semibold mb-0">14,327 <span
                        class="text-success font-size-sm font-weight-normal"><i class="icon-arrow-up12"></i>
                        (+2.9%)</span></h5>
                <span class="badge badge-mark border-success mr-1"></span> <span class="text-muted">Jun 16, 10:00
                    am</span>
            </div>
        </div>
        <div class="d-flex align-items-center mb-3 mb-md-0">
            <div id="today-progress"></div>
            <div class="ml-3">
                <h5 class="font-weight-semibold mb-0">14,327 <span
                        class="text-success font-size-sm font-weight-normal"><i class="icon-arrow-up12"></i>
                        (+2.9%)</span></h5>
                <span class="badge badge-mark border-success mr-1"></span> <span class="text-muted">Jun 16, 10:00
                    am</span>
            </div>
        </div>
    </div>

</div>
<!-- /support tickets -->

templates/dashboards/application/table.html
{% load static %}

<!-- Individual column searching (selects) -->
<div class="panel panel-flat">
    <div class="panel-heading">
        <div class="row justify-content-center">
            <nav aria-label="navigation">
                <ul class="pagination">
                    <li class="page-item">

                        <a style="background-color: green;" class="btn btn-primary"
                            href="{% url 'companies:live_app_score_pred' %}">
                            Request Application score
                        </a>

                    </li>
                    <!-- <li style="padding-left: 35px;" class="page-item pull-right">
                        <button class="btn btn-primary page-link" id="next">Next</button>
                    </li> -->
                </ul>
            </nav>
        </div>
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
                <li><a data-action="reload"></a></li>
                <li><a data-action="close"></a></li>
            </ul>
        </div>
    </div>

    <div class="panel-body">
        {% include 'dashboards/filters.html' %}
    </div>

    <table class="table table-sm" id="application_classifier_list_data" data-toggle="table"
        url="{% url 'companies:application_scoring_view' %}">
        <thead>
            <tr>
                <th>Officer</th>
                <th>Colleteral</th>
                <th>Amount Applied For</th>
                <th>Social Media Assessment</th>
                <th>Credit History Assessment</th>
                <th>Pyschometric Assessment</th>
                <th>Text Assessment Analytics</th>
                <th>Overal Assessment</th>
                <th>Decision</th>
                <th><i class="icon-arrow-down12"></i></th>


            </tr>
        </thead>
        <tbody id="application_classifier_listing">
        </tbody>
    </table>
</div>
<div class="row justify-content-center">
    <nav aria-label="navigation">
        <ul class="pagination">
            <li class="page-item">
                <button class="btn btn-primary page-link" id="previous">Previous</button>
            </li>
            <li style="padding-left: 35px;" class="page-item pull-right">
                <button class="btn btn-primary page-link" id="next">Next</button>
            </li>
        </ul>
    </nav>
</div>
<!-- /individual column searching (selects) -->
<script src="{% static 'global_assets/js/main/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/chart.bundle.js' %}"></script>
<script src="{% static 'account/assets/js/application_scoring.js' %}"></script>